### PR TITLE
Fix loading collision types in Android

### LINKED ISSUE #95: Memory Leak: OpenFile should return a unique_ptr instead of a raw ptr

### PR DESCRIPTION
**Pull request by tlein**
Resolves #95

### CODE REVIEW

File: Engine/Src/Ancona/Core2D/Systems/Collision/CollisionSystem.cpp [hunk 1]
```diff
@@ -20,18 +21,15 @@ CollisionSystem::CollisionSystem(const std::string & name, SystemManager & manag
 void CollisionSystem::OnLoad()
 {
     CreateType(NONE_COLLISION_TYPE);
-    if (FileOperations::IsFile("project/collision-types.json"))
+    auto fileStream = FileOperations::GetInputFileStream("project/collision-types.json");
```
Comment (tlein) [inline Engine/Src/Ancona/Core2D/Systems/Collision/CollisionSystem.cpp]: We should instead fix the FileOperations::IsFile function on android to check for non apk storage

File: Engine/Src/Ancona/Core2D/Systems/Collision/CollisionSystem.cpp [hunk 2]
```diff
@@ -170,6 +169,10 @@ CollisionType CollisionSystem::CreateType(const std::string &key)
     _collisionTypes.emplace(key, newType);
     _collisionTypeToKey.emplace(newType, key);
 
+
+    std::ostringstream buffer;
```
Comment (tlein) [inline Engine/Src/Ancona/Core2D/Systems/Collision/CollisionSystem.cpp]: Remove log statements

Comment (tlein) [reply Engine/Src/Ancona/Core2D/Systems/Collision/CollisionSystem.cpp]: fixed

File: Engine/Src/Ancona/Core2D/Systems/Collision/CollisionSystem.cpp [hunk 3]
```diff
@@ -20,18 +19,17 @@ CollisionSystem::CollisionSystem(const std::string & name, SystemManager & manag
...
-        reader.parse(*fileStream, collisionTypesRoot);
-        for (Json::Value & collisionType : collisionTypesRoot["collisionTypes"])
-        {
-            if (collisionType.asString() != NONE_COLLISION_TYPE)
-            {
-                CreateType(collisionType.asString());
-            }
+    auto fileStream = FileOperations::GetInputFileStream("project/collision-types.json");
+    if (!fileStream) {
+        return;
```
Comment (jeffswenson) [inline Engine/Src/Ancona/Core2D/Systems/Collision/CollisionSystem.cpp:24]: We should add an assert here.

File: Engine/Src/Ancona/System/Android/AndroidFileOperations.hpp [hunk 4]
```diff
@@ -38,7 +42,8 @@ class AndroidFileOperations
     private:
         static AAssetManager * _assetManager;
         static std::string _internalPath;
-
+        
+        static bool IsFileInNonApkStorage(const std::string & filePath);
```
Comment (jeffswenson) [inline Engine/Src/Ancona/System/Android/AndroidFileOperations.hpp]: You can put this in Android/FileOperations.cpp. Then you don't need to flag the class as friends.

File: Engine/Src/Ancona/System/Android/FileOperations.cpp [hunk 5]
```diff
@@ -56,15 +56,25 @@ bool FileOperations::IsDir(const std::string & dirPath)
 
 bool FileOperations::IsFile(const std::string & filePath)
 {
+    std::string fullInternalPath = AndroidFileOperations::internalPath() + "/" + filePath;
+    if (AndroidFileOperations::IsFileInNonApkStorage(fullInternalPath)) {
+        return true;
+    }
+    
+    return AndroidFileOperations::OpenFile(fullInternalPath) != nullptr;
```
Comment (jeffswenson) [inline Engine/Src/Ancona/System/Android/FileOperations.cpp]: This is a memory leak.

File: Engine/Src/Ancona/System/Android/AndroidFileOperations.hpp (hunk 4 above)
Comment (tlein) [reply Engine/Src/Ancona/System/Android/AndroidFileOperations.hpp]: fixed

File: Engine/Src/Ancona/System/Android/FileOperations.cpp (hunk 5 above)
Comment (tlein) [reply Engine/Src/Ancona/System/Android/FileOperations.cpp]: fixed

File: Engine/Src/Ancona/Core2D/Systems/Collision/CollisionSystem.cpp (hunk 3 above)
Comment (tlein) [reply Engine/Src/Ancona/Core2D/Systems/Collision/CollisionSystem.cpp:24]: you could view not having the collision types as a valid option since the "NONE" type is always created and you can manually create types (like we used to)
