### PR TITLE
fix screen transition rectangle size

### LINKED ISSUE #96: Screen transition rectangle is the wrong size on smaller screens

### PR DESCRIPTION
**Pull request by tlein**
Resolves #96

### CODE REVIEW

File: Engine/Src/Ancona/Framework/Screens/AbstractScreen.cpp [hunk 1]
```diff
@@ -58,3 +58,8 @@ void AbstractScreen::Exiting(float delta)
     _screenManager.Window.setView(_defaultCam);
     _screenManager.Window.draw(_transitionRect);
 }
+
+void AbstractScreen::SetTransitionRect(int width, int height)
```
Comment (jeffswenson) [inline Engine/Src/Ancona/Framework/Screens/AbstractScreen.cpp]: Instead of creating this, we should use the screenManager reference in the constructor to do the right thing at construction time.

**Review by jeffswenson — CHANGES_REQUESTED** [review]

File: Engine/Src/Ancona/Framework/Screens/AbstractScreen.cpp (hunk 1 above)
Comment (tlein) [reply Engine/Src/Ancona/Framework/Screens/AbstractScreen.cpp]: fixed
